/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/admin/adminCreate': RouteRecordInfo<'/admin/adminCreate', '/admin/adminCreate', Record<never, never>, Record<never, never>>,
    '/admin/adminHome': RouteRecordInfo<'/admin/adminHome', '/admin/adminHome', Record<never, never>, Record<never, never>>,
    '/admin/adminLogin': RouteRecordInfo<'/admin/adminLogin', '/admin/adminLogin', Record<never, never>, Record<never, never>>,
    '/admin/adminManagement': RouteRecordInfo<'/admin/adminManagement', '/admin/adminManagement', Record<never, never>, Record<never, never>>,
    '/admin/adminNotapproved': RouteRecordInfo<'/admin/adminNotapproved', '/admin/adminNotapproved', Record<never, never>, Record<never, never>>,
    '/admin/adminReported': RouteRecordInfo<'/admin/adminReported', '/admin/adminReported', Record<never, never>, Record<never, never>>,
    '/admin/adminSubjectManagement': RouteRecordInfo<'/admin/adminSubjectManagement', '/admin/adminSubjectManagement', Record<never, never>, Record<never, never>>,
    '/admin/adminUsermanagement': RouteRecordInfo<'/admin/adminUsermanagement', '/admin/adminUsermanagement', Record<never, never>, Record<never, never>>,
    '/allUserQuizzes/[id]/': RouteRecordInfo<'/allUserQuizzes/[id]/', '/allUserQuizzes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/create': RouteRecordInfo<'/create', '/create', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/IndexPage': RouteRecordInfo<'/IndexPage', '/IndexPage', Record<never, never>, Record<never, never>>,
    '/management': RouteRecordInfo<'/management', '/management', Record<never, never>, Record<never, never>>,
    '/mypage': RouteRecordInfo<'/mypage', '/mypage', Record<never, never>, Record<never, never>>,
    '/mypage/profile': RouteRecordInfo<'/mypage/profile', '/mypage/profile', Record<never, never>, Record<never, never>>,
    '/notApprovedQuizzes/[id]/': RouteRecordInfo<'/notApprovedQuizzes/[id]/', '/notApprovedQuizzes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/quizzes/[id]/': RouteRecordInfo<'/quizzes/[id]/', '/quizzes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/reportedQuizzes/[id]/': RouteRecordInfo<'/reportedQuizzes/[id]/', '/reportedQuizzes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/userQuizzes/[id]/': RouteRecordInfo<'/userQuizzes/[id]/', '/userQuizzes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
